import { useState, useEffect } from 'react'
import axios from 'axios'
import {
  RadarChart, Radar, PolarGrid, PolarAngleAxis, ResponsiveContainer,
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip
} from 'recharts'

const MOCK_REPORT = {
  week_of: 'April 11, 2026',
  weekly_data: [
    { day: 'Mon', deep_work_hours: 6, distraction_events: 3, flow_sessions: 2, twin_divergence: 22, is_super_day: true, is_burnout_day: false },
    { day: 'Tue', deep_work_hours: 3, distraction_events: 7, flow_sessions: 0, twin_divergence: 63, is_super_day: false, is_burnout_day: true },
    { day: 'Wed', deep_work_hours: 5, distraction_events: 4, flow_sessions: 1, twin_divergence: 38, is_super_day: false, is_burnout_day: false },
    { day: 'Thu', deep_work_hours: 7, distraction_events: 2, flow_sessions: 3, twin_divergence: 18, is_super_day: true, is_burnout_day: false },
    { day: 'Fri', deep_work_hours: 4, distraction_events: 5, flow_sessions: 1, twin_divergence: 47, is_super_day: false, is_burnout_day: false },
    { day: 'Sat', deep_work_hours: 2, distraction_events: 6, flow_sessions: 0, twin_divergence: 58, is_super_day: false, is_burnout_day: false },
    { day: 'Sun', deep_work_hours: 5, distraction_events: 2, flow_sessions: 2, twin_divergence: 25, is_super_day: false, is_burnout_day: false },
  ],
  summary: {
    avg_divergence: 39,
    total_flow_sessions: 9,
    super_days_count: 2,
    best_day: 'Thursday',
    worst_day: 'Tuesday'
  },
  narrative: "This week, your twin logged 32 hours of deep work across 7 days — above your monthly average. Your Thursday was your strongest day: low divergence, 3 flow sessions, high output. But Tuesday told a different story — 7 distraction events and your worst divergence of the week. The pattern your twin keeps seeing: your distraction chains almost always start with email → news. You broke that chain successfully 4 times this week. Keep catching it at that first link.",
  success_patterns: [
    '10-min walk → 2+ hours deep work',
    '8 AM start → 40% higher output',
    'No email before 10 AM on power days'
  ],
  insights: [
    "Your biggest focus killer is the Tuesday 4:30 PM energy crash",
    "On your 2 Super Days, you logged 3+ Flow Sessions each",
    "Your distraction chains always start with Email → News — catch it at step 1"
  ]
}

export default function HabitDNA() {
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetch = async () => {
      try {
        const { data } = await axios.get('/api/habit-dna', { timeout: 3000 })
        setReport(data)
      } catch {
        setReport(MOCK_REPORT)
      }
      setLoading(false)
    }
    fetch()
  }, [])

  if (loading) {
    return (
      <div>
        <div className="page-header">
          <h1 className="page-title">Habit DNA Report</h1>
        </div>
        <div className="card skeleton" style={{ height: '300px' }} />
      </div>
    )
  }

  const r = report
  const radarData = r.weekly_data.map(d => ({
    day: d.day,
    'Deep Work': d.deep_work_hours,
    'Flow Sessions': d.flow_sessions * 2,
    'Distractions': d.distraction_events,
  }))

  return (
    <div>
      <div className="page-header flex items-center justify-between">
        <div>
          <h1 className="page-title">Habit DNA Report</h1>
          <p className="page-subtitle">Week of {r.week_of} · AI-generated narrative</p>
        </div>
        <button id="refresh-dna-btn" className="btn btn-primary btn-sm" onClick={() => { setLoading(true); setTimeout(() => { setReport(MOCK_REPORT); setLoading(false) }, 500) }}>
          Regenerate
        </button>
      </div>

      {/* Narrative */}
      <div className="card card-glow-violet" style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
          <div style={{
            width: '40px', height: '40px', borderRadius: '12px',
            background: 'linear-gradient(135deg, var(--violet), #9d4edd)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '1.2rem', flexShrink: 0
          }}>🧬</div>
          <div>
            <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1.05rem' }}>Your Weekly Story</div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Generated by Twin Coach AI</div>
          </div>
        </div>
        <p style={{ fontSize: '0.95rem', lineHeight: 1.8, color: 'var(--text-primary)', borderLeft: '3px solid var(--violet)', paddingLeft: '16px' }}>
          {r.narrative}
        </p>
      </div>

      {/* Summary cards */}
      <div className="grid-4" style={{ marginBottom: '24px' }}>
        {[
          { label: 'Avg Divergence', value: `${r.summary.avg_divergence}%`, color: r.summary.avg_divergence < 40 ? 'var(--emerald)' : 'var(--amber)', icon: '📊' },
          { label: 'Flow Sessions', value: r.summary.total_flow_sessions, color: 'var(--violet-light)', icon: '⚡' },
          { label: 'Super Days', value: r.summary.super_days_count, color: '#fbbf24', icon: '🌟' },
          { label: 'Best Day', value: r.summary.best_day, color: 'var(--emerald)', icon: '🏆' },
        ].map(({ label, value, color, icon }) => (
          <div key={label} className="card card-sm" style={{ textAlign: 'center' }}>
            <div style={{ fontSize: '1.4rem', marginBottom: '8px' }}>{icon}</div>
            <div style={{ fontFamily: 'var(--font-display)', fontSize: '1.5rem', fontWeight: 700, color }}>{value}</div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '4px' }}>{label}</div>
          </div>
        ))}
      </div>

      <div className="grid-2" style={{ marginBottom: '24px' }}>
        {/* Bar chart */}
        <div className="card">
          <h2 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1rem', marginBottom: '20px' }}>
            📅 Weekly Breakdown
          </h2>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={r.weekly_data}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" />
              <XAxis dataKey="day" tick={{ fill: '#5a5a7a', fontSize: 11 }} />
              <YAxis tick={{ fill: '#5a5a7a', fontSize: 11 }} />
              <Tooltip contentStyle={{ background: '#14142a', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', color: '#f0f0ff' }} />
              <Bar dataKey="deep_work_hours" name="Deep Work (hrs)" fill="#7c3aed" radius={[4,4,0,0]} />
              <Bar dataKey="distraction_events" name="Distractions" fill="#f43f5e" radius={[4,4,0,0]} />
              <Bar dataKey="flow_sessions" name="Flow Sessions" fill="#06b6d4" radius={[4,4,0,0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        {/* Day cards */}
        <div className="card">
          <h2 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1rem', marginBottom: '16px' }}>
            📆 Day-by-Day Divergence
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {r.weekly_data.map((d) => (
              <div key={d.day} style={{
                display: 'flex', alignItems: 'center', gap: '12px',
                padding: '8px 12px',
                background: d.is_super_day ? 'rgba(16,185,129,0.08)' : d.is_burnout_day ? 'rgba(244,63,94,0.08)' : 'var(--bg-glass)',
                border: `1px solid ${d.is_super_day ? 'rgba(16,185,129,0.3)' : d.is_burnout_day ? 'rgba(244,63,94,0.25)' : 'var(--border)'}`,
                borderRadius: 'var(--radius-sm)'
              }}>
                <div style={{ width: '32px', fontWeight: 700, fontSize: '0.8rem', color: 'var(--text-secondary)' }}>{d.day}</div>
                <div style={{ flex: 1 }}>
                  <div className="risk-bar" style={{ marginBottom: 0 }}>
                    <div className="risk-fill" style={{
                      width: `${d.twin_divergence}%`,
                      background: d.twin_divergence < 25 ? 'linear-gradient(90deg,var(--emerald),#34d399)' : d.twin_divergence < 55 ? 'linear-gradient(90deg,var(--amber),#fcd34d)' : 'linear-gradient(90deg,var(--rose),#f87171)'
                    }} />
                  </div>
                </div>
                <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.78rem', width: '36px', textAlign: 'right', color: d.twin_divergence < 30 ? 'var(--emerald)' : 'var(--text-secondary)' }}>
                  {d.twin_divergence}%
                </div>
                {d.is_super_day && <span style={{ fontSize: '0.75rem' }}>⭐</span>}
                {d.is_burnout_day && <span style={{ fontSize: '0.75rem' }}>🔥</span>}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Insights + Patterns */}
      <div className="grid-2">
        <div className="card">
          <h2 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1rem', marginBottom: '16px' }}>
            💡 Twin Insights
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {r.insights.map((insight, i) => (
              <div key={i} style={{
                display: 'flex', gap: '12px', alignItems: 'flex-start',
                padding: '12px 14px',
                background: 'rgba(124,58,237,0.06)',
                border: '1px solid rgba(124,58,237,0.2)',
                borderRadius: 'var(--radius-sm)'
              }}>
                <span style={{ color: 'var(--violet-light)', fontWeight: 700, flexShrink: 0 }}>0{i + 1}</span>
                <span style={{ fontSize: '0.87rem', lineHeight: 1.6 }}>{insight}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="card">
          <h2 style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: '1rem', marginBottom: '16px' }}>
            ⚡ Verified Success Patterns
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {r.success_patterns.map((pattern, i) => (
              <div key={i} style={{
                display: 'flex', gap: '12px', alignItems: 'center',
                padding: '14px',
                background: 'rgba(16,185,129,0.06)',
                border: '1px solid rgba(16,185,129,0.2)',
                borderRadius: 'var(--radius-sm)'
              }}>
                <span style={{ fontSize: '1.2rem' }}>✅</span>
                <span style={{ fontSize: '0.875rem', lineHeight: 1.5, fontWeight: 500 }}>{pattern}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
